version: "3.8"
services:
  flask-app:
    # image: olayodech:flask-app-new
    build: .
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://olayodech:12345@db/product-dev-db
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    depends_on: 
      - db
        # nginx
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'product-dev-db'
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - target: 3306
        published: 3306
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   volumes:
  #     - type: bind
  #       source: ./nginx/nginx.conf
  #       target: /etc/nginx/nginx.conf

volumes:
  my-db: