version: "3.8"
services:
  flask-app:
    build: ./application
    ports:
      - target: 5000
        published: 5000
        protocol: tcp

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf

volumes:
  jenkins: